---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: gcr.io/cloud-builders/go
inputs:
- name: cloud-service-broker
  path: broker-source
outputs:
- name: client-windows
run:
  dir: broker-source
  path: go.ash
  args: ['build', '-o', '../client-windows/cloud-service-broker-windows.exe']
params:
  PROJECT_ROOT: github.com/cloudfoundry-incubator/cloud-service-broker
  GOOS: windows
  GOARCH: amd64
